### ISSUE TITLE
No shop slot limit

### ISSUE THREAD

**Issue by physi3** [ollydevulder/slots-project#1]
There is no shop slot limit.

**Comment by ollydevulder** [comment]
Can you be more specific in this issue? 
Unsure as to the exact nature of the issue.

**Comment by ollydevulder** [comment]
Could you explain the nature of the bug and how it can be replicated?

**Comment by physi3** [comment]
There isn't a limit to the number of shop slots you can have.

**Comment by physi3** [comment]
When you add slots to shops.

**Comment by ollydevulder** [comment]
Ok epic.
